language: python

install:
  - pip install tox

script:
  - tox

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27-dj1.11
  - python: 3.4
    env: TOXENV=py34-dj1.11
  - python: 3.5
    env: TOXENV=py35-dj1.11,flake8,coverage
  - python: 3.6
    env: TOXENV=py36-dj1.11,docs
